"""Add coverImageUrl to Manga model

Revision ID: 285634db527f
Revises: 6e379c37a20c
Create Date: 2025-01-21 18:50:35.324952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285634db527f'
down_revision = '6e379c37a20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
