"""Add is_featured cokumn to Manga

Revision ID: 6e379c37a20c
Revises: 
Create Date: 2025-01-17 15:16:08.791145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e379c37a20c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False,server_default=sa.text('0')))


    op.execute("UPDATE manga SET is_featured = 0")
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.alter_column('is_featured', server_default=None)
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manga', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
